id: P006994
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:55.663644
source_metadata:
  id: bdr:W29218
  title: དཔལ་ལྡན་འབྲུག་པའི་རིང་ལུགས་དཀྱིལ་ཆོག་གི་སྔགས་ཀློག་དགོས་མཁོ་གཞན་དང་བཅས་པ་དངོས་གྲུབ་མྱུར་སྦྱིན།
  author: ''
  volumes:
    7fb923cdc95c4c7fbf5591fd7902890c:
      image_group_id: I1KG17971
      title: Volume 1 of dpal ldan 'brug pa'i ring lugs dkyil chog gi sngags klog
        dgos mkho gzhan dang bcas pa dngos grub myur sbyin/
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
