id: opecha:P006994
initial_creation_type: ocr
source_metadata:
  id: bdr:W29218
  title: དཔལ་ལྡན་འབྲུག་པའི་རིང་ལུགས་དཀྱིལ་ཆོག་གི་སྔགས་ཀློག་དགོས་མཁོ་གཞན་དང་བཅས་པ་དངོས་གྲུབ་མྱུར་སྦྱིན།
  volume: ''
  author: ''
