id: P006994
initial_creation_type: ocr
source_metadata:
  id: bdr:W29218
  title: དཔལ་ལྡན་འབྲུག་པའི་རིང་ལུགས་དཀྱིལ་ཆོག་གི་སྔགས་ཀློག་དགོས་མཁོ་གཞན་དང་བཅས་པ་དངོས་གྲུབ་མྱུར་སྦྱིན།
  author: ''
  volumes:
    9ce26071b3dd4cb4bd4a69b5fbb2c0bb:
      image_group_id: I1KG17971
      title: ''
      volume_number: 1
      total_pages: 324
ebook_metadata:
  title: དཔལ་ལྡན་འབྲུག་པའི་རིང་ལུགས་དཀྱིལ་ཆོག་གི་སྔགས་ཀློག་དགོས་མཁོ་གཞན་དང་བཅས་པ་དངོས་གྲུབ་མྱུར་སྦྱིན།
  author: ''
  sku: P006994
  cover: cover.jpg
  layers:
  - pagination
