id: IB93EA4C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:30:38+00:00'
last_modified: '2022-06-08T10:54:00.246009+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29218
  title: དཔལ་ལྡན་འབྲུག་པའི་རིང་ལུགས་དཀྱིལ་ཆོག་གི་སྔགས་ཀློག་དགོས་མཁོ་གཞན་དང་བཅས་པ་དངོས་གྲུབ་མྱུར་སྦྱིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EBFE:
      image_group_id: I1KG17971
      title: Volume 1 of dpal ldan 'brug pa'i ring lugs dkyil chog gi sngags klog
        dgos mkho gzhan dang bcas pa dngos grub myur sbyin/
      total_pages: 324
      order: 1
      base_file: EBFE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
